name: Release

on:
  push:
    tags: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Get version
    runs-on: ubuntu-latest
    steps:
      - id: version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Show version
        run: echo ${{ steps.version.outputs.VERSION }}

    outputs:
      version: ${{ steps.version.outputs.VERSION }}

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Remove binaries from cache
        run: rm -vf target/wasm32-unknown-unknown/release/*.wasm

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install binaryen
        run: |
          wget -c https://github.com/WebAssembly/binaryen/releases/download/version_110/binaryen-version_110-x86_64-linux.tar.gz -O - | tar -xz -C .
          sudo cp binaryen-version_110/bin/wasm-opt /usr/bin/

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build
        run: make build

      - name: Generate dns env file
        run: node dev/generateEnv.js dns-frontend/.env
        env:
          PATH_TO_META: ./target/wasm32-unknown-unknown/release/dns.meta.wasm
          PROGRAM_ID: ${{ secrets.DNS_PROGRAM_ID }}

      - name: Generate goc env file
        run: node dev/generateEnv.js goc-frontend/.env
        env:
          PATH_TO_META: ./target/wasm32-unknown-unknown/release/game_of_chance.meta.wasm
          PROGRAM_ID: ${{ secrets.GOC_PROGRAM_ID }}

      - name: Rename binaries according to version
        run: |
          cd target/wasm32-unknown-unknown/release
          for WASM in *.wasm; do
            if [[ $WASM == *.opt.wasm ]]; then
              NAME="${WASM%.opt.wasm}"
              EXT="opt.wasm"
            elif [[ $WASM == *.meta.wasm ]]; then
              NAME="${WASM%.meta.wasm}"
              EXT="meta.wasm"
            else
              NAME="${WASM%.wasm}"
              EXT="wasm"
            fi
            mv "$WASM" "$NAME-${{ needs.prepare.outputs.version }}.$EXT"
          done

      - name: Build frontend
        run: sudo yarn build:all

      - name: Copy build
        run: |
          cp dns-frontend/build/dns.html .
          cp goc-frontend/build/goc.html .

      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          path: ./target/wasm32-unknown-unknown/release/*.wasm

      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          path: ./*.html

  publish:
    name: Publish binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: artifact/*
